import Link from "next/link";
import { AdminStatusBadge } from "@/components/admin-status-badge";
import { Button } from "@/components/ui/button";
import { editHref, type AdminRecord } from "@/lib/admin-types";

export function AdminRecordList({
  records,
  empty,
}: {
  records: AdminRecord[];
  empty: string;
}) {
  if (!records.length) {
    return <p className="mt-4 text-sm text-cream/55">{empty}</p>;
  }
  return (
    <ul className="mt-4 divide-y divide-white/10 rounded-xl border border-white/10 bg-card">
      {records.map((record) => (
        <li
          key={`${record.kind}-${record.slug}`}
          className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between"
        >
          <div className="min-w-0">
            <p className="font-medium text-cream">{record.title}</p>
            <p className="mt-1 text-xs text-cream/50">{record.path}</p>
            {record.generatedBy === "agent" || record.pageType === "country" ? (
              <p className="mt-1 text-xs text-amber/80">
                {record.generatedBy === "agent" ? "Generated by the agent" : "Country guide"}
              </p>
            ) : null}
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <AdminStatusBadge status={record.status} />
            <Button asChild variant="outline" size="sm" className="min-h-10">
              <Link href={editHref(record)}>Edit</Link>
            </Button>
            <Button asChild variant="ghost" size="sm" className="min-h-10">
              <Link href={record.path}>View</Link>
            </Button>
          </div>
        </li>
      ))}
    </ul>
  );
}
